# Generated by Django 3.0.3 on 2020-02-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200208_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_mine',
            field=models.BooleanField(default=False),
        ),
    ]
