# Generated by Django 3.0.3 on 2020-02-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200208_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
