# Generated by Django 3.0.2 on 2020-02-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_board_correct_flag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='correct_flag_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='mine_count',
        ),
        migrations.AddField(
            model_name='game',
            name='correct_flag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='mine_count',
            field=models.IntegerField(default=0),
        ),
    ]
