# Generated by Django 3.0.3 on 2020-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_board_is_mine'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='mine_count',
            field=models.IntegerField(default=0),
        ),
    ]
