# Generated by Django 3.0.3 on 2020-02-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200208_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='xCoord',
            new_name='x_coord',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='yCoord',
            new_name='y_coord',
        ),
    ]
